# Generated by Django 5.1.2 on 2025-01-14 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sneaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('article', models.CharField(max_length=15)),
                ('in_stock', models.PositiveSmallIntegerField()),
                ('raiting', models.PositiveSmallIntegerField()),
                ('size', models.JSONField(default=list)),
                ('price', models.IntegerField()),
                ('sex', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=30)),
                ('compound', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=30)),
            ],
        ),
    ]
