# Generated by Django 5.1.2 on 2025-01-14 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sneaker',
            options={'verbose_name': 'Кроссовки', 'verbose_name_plural': 'Кроссовки'},
        ),
        migrations.AlterField(
            model_name='sneaker',
            name='Country',
            field=models.CharField(max_length=30, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='sneaker',
            name='article',
            field=models.CharField(max_length=15, verbose_name='Артикль'),
        ),
        migrations.AlterField(
            model_name='sneaker',
            name='color',
            field=models.JSONField(default=list, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='sneaker',
            name='compound',
            field=models.CharField(max_length=100, verbose_name='Состав'),
        ),
        migrations.AlterField(
            model_name='sneaker',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='sneaker',
            name='in_stock',
            field=models.PositiveSmallIntegerField(verbose_name='В налиии'),
        ),
        migrations.AlterField(
            model_name='sneaker',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='sneaker',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='sneaker',
            name='raiting',
            field=models.PositiveSmallIntegerField(verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='sneaker',
            name='sex',
            field=models.CharField(max_length=10, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='sneaker',
            name='size',
            field=models.JSONField(default=list, verbose_name='Размер'),
        ),
    ]
