# Generated by Django 5.1.2 on 2025-01-14 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_alter_sneaker_options_alter_sneaker_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sneaker',
            old_name='Country',
            new_name='country',
        ),
    ]
