# Generated by Django 5.1.2 on 2025-01-14 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0004_sneaker_main_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneaker',
            name='description',
            field=models.CharField(max_length=600, verbose_name='Описание'),
        ),
    ]
