# Generated by Django 5.1.2 on 2025-01-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0007_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователи', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='user',
            name='sneakers',
            field=models.ManyToManyField(related_name='Basket_item', to='shopapp.sneaker', verbose_name='Кроссовки в корзине'),
        ),
    ]
