# Generated by Django 5.1.2 on 2025-01-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0008_alter_user_options_user_sneakers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sneakers',
            field=models.ManyToManyField(blank=True, related_name='Basket_item', to='shopapp.sneaker', verbose_name='Кроссовки в корзине'),
        ),
    ]
